### ISSUE TITLE
[BUG] sendMessage doesn't like being called off thread sometimes

### ISSUE THREAD

**Issue by CoolMineman** [CoolMineman/CheaterDeleter#8]
```
[23:26:43] [CheaterDeleter/INFO] (Minecraft) [STDERR]: net.minecraft.util.crash.CrashException: Sending packet
[23:26:43] [CheaterDeleter/INFO] (Minecraft) [STDERR]: 	at net.minecraft.server.network.ServerPlayNetworkHandler.sendPacket(ServerPlayNetworkHandler.java:1075)
[23:26:43] [CheaterDeleter/INFO] (Minecraft) [STDERR]: 	at net.minecraft.server.network.ServerPlayNetworkHandler.sendPacket(ServerPlayNetworkHandler.java:1051)
[23:26:43] [CheaterDeleter/INFO] (Minecraft) [STDERR]: 	at net.minecraft.server.network.ServerPlayerEntity.sendMessage(ServerPlayerEntity.java:1054)
[23:26:43] [CheaterDeleter/INFO] (Minecraft) [STDERR]: 	at io.github.coolmineman.cheaterdeleter.modules.CDModule.flag(CDModule.java:29)
[23:26:43] [CheaterDeleter/INFO] (Minecraft) [STDERR]: 	at io.github.coolmineman.cheaterdeleter.modules.combat.VerifyAttackAngle.onAttack(VerifyAttackAngle.java:36)
[23:26:43] [CheaterDeleter/INFO] (Minecraft) [STDERR]: 	at io.github.coolmineman.cheaterdeleter.events.PlayerAttackListener.lambda$2(PlayerAttackListener.java:26)
[23:26:43] [CheaterDeleter/INFO] (Minecraft) [STDERR]: 	at io.github.coolmineman.cheaterdeleter.events.PacketCallback.lambda$1(PacketCallback.java:14)
[23:26:43] [CheaterDeleter/INFO] (Minecraft) [STDERR]: 	at io.github.coolmineman.cheaterdeleter.CheaterDeleterThread.run(CheaterDeleterThread.java:29)
[23:26:43] [CheaterDeleter/INFO] (Minecraft) [STDERR]: Caused by: java.lang.NullPointerException
[23:26:43] [CheaterDeleter/INFO] (Minecraft) [STDERR]: 	at net.minecraft.network.ClientConnection.localvar$zfc000$onSendPacket(ClientConnection.java:1055)
[23:26:43] [CheaterDeleter/INFO] (Minecraft) [STDERR]: 	at net.minecraft.network.ClientConnection.send(ClientConnection.java)
[23:26:43] [CheaterDeleter/INFO] (Minecraft) [STDERR]: 	at net.minecraft.server.network.ServerPlayNetworkHandler.sendPacket(ServerPlayNetworkHandler.java:1068)
[23:26:43] [CheaterDeleter/INFO] (Minecraft) [STDERR]: 	... 7 more
```

**Comment by CoolMineman** [comment]
unable to reproduce :concern:
